### ISSUE TITLE
Openshift service failed to start even after executing "vagrant service-manager start docker"

### ISSUE THREAD

**Issue by amit82github** [projectatomic/vagrant-service-manager#258] opened 2016-06-08 07:07 UTC
Openshift service failed to start even after executing "vagrant service-manager start docker". But when i am executing the command "vagrant service-manager restart docker" it starts both docker and openshift services which is expected.

```
$  vagrant service-manager status
Configured services:
docker - running
openshift - running
kubernetes - stopped

$ vagrant service-manager stop docker

$ vagrant service-manager status
Configured services:
docker - stopped
openshift - stopped
kubernetes - stopped

$ vagrant service-manager start docker

$ vagrant service-manager status
Configured services:
docker - running
openshift - stopped
kubernetes - stopped

$ vagrant service-manager restart docker

$ sleep 30; vagrant service-manager status
Configured services:
docker - running
openshift - running
kubernetes - stopped

$ vagrant plugin list
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.2.2)
  Version Constraint: 1.2.2
vagrant-service-manager (1.1.0.beta.1)
  Version Constraint: 1.1.0.beta.1
vagrant-sshfs (1.1.0)
  Version Constraint: 1.1.0

$ cat /etc/fedora-release 
Fedora release 23 (Twenty Three)

$ vagrant -v
Vagrant 1.7.4
```

**Comment by navidshaikh** [comment] 2016-06-15 11:00
duplicate of #263. See https://github.com/projectatomic/vagrant-service-manager/issues/263#issuecomment-225838673 for explanation.

**Closed as completed by navidshaikh** 2016-06-15 11:00 UTC
