### ISSUE TITLE
service-manager box ip --script-readable not working

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#253] opened 2016-06-07 11:31 UTC
Vagrant service-manger box ip --script-readable should also display routable IP address of the running VM, as for other parameters it does give output 

```
$ vagrant.exe service-manager box ip --script-readable
Usage: vagrant service-manager box <sub-command> [options]
Sub-Command:
      version    display version and release information about the running VM
      ip         display routable IP address of the running VM

Options:
      --script-readable  display information in a script readable format
      -h, --help         print this help

Examples:
      vagrant service-manager box version
      vagrant service-manager box ip
      vagrant service-manager box version --script-readable
```

**Comment by budhrg** [comment] 2016-06-07 11:37
@naina-verma here the examples for this command is wrong and culprit for this issue. 
Example should only contain `vagrant service-manager box ip`  and it has been fixed now. You might be using version 1.0.2. Could you verify it with 1.1.0.aplha version?

**Comment by brgnepal** [comment] 2016-06-07 12:55
Duplicate of #252

**Closed as completed by brgnepal** 2016-06-07 12:55 UTC
