### ISSUE TITLE
Document how to configure OpenShift with custom image tag, registry etc 

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#362] opened 2016-08-01 13:07 UTC
Hi,

It seems the documentation on configuring OpenShift with custom image tag, registry has be removed by mistake. Unable to find the doc from past five minutes in both here and ADB repo.

May be its there but its quite not visible properly.

It looks like something this mentioned in this [quick start of release v1.0.0](https://github.com/projectatomic/vagrant-service-manager/tree/v1.0.0#quick-start) 3rd and 4th points.

**Comment by brgnepal** [comment] 2016-08-01 13:08
cc @Preeticp

**Comment by Preeticp** [comment] 2016-08-01 17:15
@budhrg this documentation exists in ADB usage document, in the using ADB with host based tools section, as discussed earlier.

**Comment by brgnepal** [comment] 2016-08-02 06:50
Found the docs [here](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-the-adb-with-host-based-tools-eclipse-and-clis) as we decided to move it there. This will be more important in customizing OpenShift I would suggest here to make a reference of it in VSM repo. Something inside the sections like configurations etc etc and then point to this docs.

**Comment by brgnepal** [comment] 2016-09-16 10:26
@bexelbie I think this feature is getting hidden in some sense since it is now not visible properly in VSM and nor in ADB README directly. 

Even inside ADB, it is only mentioned in [using.rst](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst) page under section "Using ADB with host-based tools (Eclipse and CLIs) # 3".

Is there any way to make such feature visible?
Like we can give users all options they can try in separate docs.

**Comment by Preeticp** [comment] 2016-09-19 08:41
+1 @budhrg for giving users all the options they can try. Could you please mention which options you would like to cover and the relevant details, based on that, a decision can be arrived at, as to whether we need different sections for those options within Usage doc or we need separate docs for each of the option. Also depending on what needs to be covered we may want to create a separate issue for this in ADB repo, and linking VSM repo to those docs/sections can be done at the same time.

**Comment by hferentschik** [comment] 2016-10-28 08:10
@budhrg, just to be clear - you are talking about these options, right?
- config.servicemanager.openshift_docker_registry 
- config.servicemanager.openshift_image_name 
- config.servicemanager.openshift_image_tag 

My first question is really whether these options are actually still working? This this functionality there? I was hoping though, since this is imo also the solution to how to use/upgrade to a newer OpenShift version w/o rebuilding/releasing the whole box (ADB/CDK). AFAIU though this is not working as intended anymore.

**Comment by hferentschik** [comment] 2016-10-28 08:13
Hmm, the options are actually still in the code. No idea whether it works though under the hood in the VM. If so, these options need indeed to be documented here again.

**Comment by brgnepal** [comment] 2016-10-28 09:10
Yes @hferentschik . These options works and it is there in the code. We need to document it.

**Comment by hferentschik** [comment] 2016-10-28 12:36
> These options works and it is there in the code.

Cool. Then I wonder why this was a no go for the case where someone wanted to use CDK 2.2 with
the latest OpenShift version. This is exactly why we added this in the first place. Yes, you need an image download in this case, but that does not matter imo. @LalatenduMohanty WDYT?

>  We need to document it.

+1

**Comment by LalatenduMohanty** [comment] 2016-10-28 14:06
@hferentschik  SCCLI works behind the scene to download the new images mentioned and set it up. However we used to skip the code for CDK. So it will not work for CDK 2.2 but works for ADB. Recently we enabled it for CDK too. So any release post adb-utils version 2.0  these options will work for CDK too.

**Comment by brgnepal** [comment] 2016-10-28 14:59
> any release post adb-utils version 2.0 these options will work for CDK too.

:+1:

**Comment by hferentschik** [comment] 2016-11-07 12:59
Fixed via pull request #437

**Closed as completed** 2016-11-07 12:58 UTC
Labels: component/documentation
