### ISSUE TITLE
service-manager stop doesn't work

### ISSUE THREAD

**Issue by anushshetty** [projectatomic/vagrant-service-manager#251] opened 2016-06-07 11:10 UTC
With the latest nightly build, `vagrant service-manager stop <service>` doesn't work.

[ashetty@dhcp35-129 rhel-ose]$ vagrant service-manager status openshift 
openshift - running

[ashetty@dhcp35-129 rhel-ose]$ vagrant service-manager stop openshift

[ashetty@dhcp35-129 rhel-ose]$ vagrant service-manager status openshift
openshift - running

[ashetty@dhcp35-129 rhel-ose]$ vagrant service-manager status openshift
openshift - running

**Comment by brgnepal** [comment] 2016-06-07 15:02
@anushshetty I am not able to reproduce it.
Make sure you are running latest vagrant service-manager plugin i.e `1.1.0.beta.1`.

```
$ vagrant plugin list
vagrant-registration (1.2.2)
vagrant-service-manager (1.1.0.beta.1)
  - Version Constraint: 1.1.0.beta.1
```

Check my logs:

```
$ vagrant service-manager stop -h
stops the service

Usage: vagrant service-manager stop <service> [options]

Service:
    A service provided by sccli. For example:
     docker, kubernetes, openshift etc

Options:
      -h, --help         print this help

Examples:
  vagrant service-manager stop docker
$ vagrant service-manager status 
Configured services:
docker - running
openshift - running
kubernetes - stopped

$ vagrant service-manager stop openshift

$ vagrant service-manager status openshift
openshift - stopped
$ vagrant service-manager start openshift
$ vagrant service-manager status openshift
openshift - running
$ vagrant service-manager stop openshift  
$ vagrant service-manager status openshift
openshift - stopped

```

**Comment by ashetty1** [comment] 2016-06-09 10:54
Unable to reproduce. Please close the issue.

**Comment by brgnepal** [comment] 2016-06-09 10:59
@ashetty1 I am able to reproduce it with CDK 2.0 and vagrant service-manager 1.1.0.

**Comment by brgnepal** [comment] 2016-06-09 11:36
Closing this issue as this will not exists in CDk 2.1. The reason for this issue in CDK 2.0 is as follows:

CDK 2.0 uses internally uses old [`sccli`](https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.py) which does not recognize command like `sccli openshift start/stop` and however it return exit code zero which means success in term's of vagrant ssh communication through line `machine.communicate.test(cmd)` 

```
➜  rhel-ose git:(master) ✗ vagrant ssh       

[vagrant@rhel-cdk ~]$ sudo sccli openshift stop
usage: sccli [service_name] || [clean]
List of possible service_name: 
  k8s openshift

[vagrant@rhel-cdk ~]$ echo $?
0
```

**Closed as completed by brgnepal** 2016-06-09 11:36 UTC
