### ISSUE TITLE
service manager displaying wrong info

### ISSUE THREAD

**Issue by amit82github** [projectatomic/vagrant-service-manager#255] opened 2016-06-07 12:10 UTC
service manager status showing kubernetes as running where as the actual service in cdk is dead. 

```
$ vagrant service-manager status
Configured services:
docker - running
openshift - running
kubernetes - running

$ vagrant ssh
Last login: Tue Jun  7 07:26:00 2016 from ....

$ sudo systemctl status etcd.service 
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

$ exit
logout
Connection to .... closed.

$ vagrant -v
Vagrant 1.7.4

$ cat /etc/fedora-release
Fedora release 23 (Twenty Three)

$ vagrant plugin list
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.2.1)
  - Version Constraint: 1.2.1
vagrant-service-manager (1.1.0.beta.1)
  - Version Constraint: 1.1.0.beta.1
vagrant-sshfs (1.1.0)
  - Version Constraint: 1.1.0

```

**Comment by amit82github** [comment] 2016-06-07 12:17
Adding os version : 
$ cat /etc/fedora-release 
Fedora release 23 (Twenty Three)
$

**Comment by brgnepal** [comment] 2016-06-07 15:18
Updated with proper formatting of issue's description

**Comment by brgnepal** [comment] 2016-06-09 10:51
@amit82github this issue will not exists in CDK 2.1. 

Closing this issue. If you feel any different opinion, feel free to re-open it.

**Comment by LalatenduMohanty** [comment] 2016-06-09 11:07
@budhrg have we tested with CDK 2.1? Also have we figured out the root cause of issue? If it is a code issue then we should fix it.

**Comment by brgnepal** [comment] 2016-06-09 11:12
Closing this issue as this issue doesn't persists in CDK 2.1 RC build.

```
➜  rhel-ose git:(master) ✗ vagrant service-manager status
Configured services:
docker - running
openshift - running
kubernetes - stopped

```

**Closed as completed by brgnepal** 2016-06-09 11:12 UTC

**Comment by LalatenduMohanty** [comment] 2016-06-09 11:14
@budhrg can please explain what was the root cause of the issue and how it got fixed in latest build of CDK.

**Comment by brgnepal** [comment] 2016-06-09 11:34
CDK 2.0 uses internally uses old [`sccli`](https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.py) which does not recognize command like `sccli openshift status` and however it return exit code zero which means success in term's of vagrant ssh communication through line `machine.communicate.test(cmd)` which causes every services docker, openshift and kubernetes as running.

```
➜  rhel-ose git:(master) ✗ vagrant ssh       

[vagrant@rhel-cdk ~]$ sudo sccli kubernetes status
usage: sccli [service_name] || [clean]
List of possible service_name: 
  k8s openshift

[vagrant@rhel-cdk ~]$ echo $?
0
```
